# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manager_request_api_development
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  <<: *default
  database: manager_request_api_test

production:
  primary: &primary_production
    <<: *default
    database: manager_request_api_production
    username: manager_request_api
    password: <%= ENV["MANAGER_REQUEST_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: manager_request_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: manager_request_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: manager_request_api_production_cable
    migrations_paths: db/cable_migrate
